version: '3.8'

services:
  db:
    image: postgres:12
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: taskmanager
      POSTGRES_USER: skoroule
      POSTGRES_PASSWORD: k6567syY
    ports:
      - "5432:5432"

  task-manager:
    build:
      context: ./task_manager
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/taskmanager
      SPRING_DATASOURCE_USERNAME: skoroule
      SPRING_DATASOURCE_PASSWORD: k6567syY
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: 'true'
      SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL: 'true'
    depends_on:
      - db
    ports:
      - "8080:8080"

  task-client:
    build:
      context: ./task_client
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - task-manager

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: skoroule@example.com 
      PGADMIN_DEFAULT_PASSWORD: k6567syY
    ports:
      - "8081:80" 

volumes:
  pgdata:
